services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    restart: always
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb

networks:
  inception:


