networks:
  inception:

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/melee/data
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/melee/data

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    restart: always
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always
    volumes:
      - db:/var/lib/mysql
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    restart: always
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html


  
    
    

