networks:
  inception:

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/melee/data/wp
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/melee/data/db


services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    restart: always
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always
    volumes:
      - db:/var/lib/mysql
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    restart: always
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
  redis:
    build: ./requirements/bonus/redis/
    image: redis
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
  ftp:
    build: ./requirements/bonus/ftp/
    image: ftp
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wp:/home/${FTP_USER}
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file:
      - .env
  site:
    build: ./requirements/bonus/site/
    image: site
    restart: always
    ports:
      - "3000:3000"



  
    
    

